version: "3.8"

services:
  manitotti-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manitotti-web
    ports:
      - "8080:8080"
    depends_on:
      - manitotti-mysql
    restart: unless-stopped

  manitotti-mysql:
    image: mysql:8.0
    container_name: manitotti-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: manitotti
      MYSQL_USER: wldh25
      MYSQL_PASSWORD: mini2team
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u wldh25 -pmini2team"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - manitotti-net
    restart: always

volumes:
  mysql-data:

networks:
  manitotti-net:
    driver: bridge