spring:
  application:
    name: Manitotti

  datasource:
    url: jdbc:mysql://manitotti-mysql:3306/manitotti
    username: wldh25
    password: mini2team
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 400000
      idle-timeout: 600000  # 10분
      connection-timeout: 30000 # 30초
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jwt:
    secret: m58PSsk5UqGOwX7azDnBUpIIZfbZxXnE
    access-expiration: 360000

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace
    org.springframework.jdbc: debug

springdoc:
  swagger-ui:
    path: "/swagger-ui/index.html"
    servers:
      - url: https://mini2team.lion.it.kr
    operations-sorter: "alpha"
    tags-sorter: "alpha"
    disable-swagger-default-url: true
    try-it-out-enabled: true
    # doc-expansion: "none"
  default-consumes-media-type: "application/json"
  default-produces-media-type: "application/json"
server:
  forward-headers-strategy: framework
